FROM python:3
LABEL maintainer="olasodeadeyemi@gmail.com"
LABEL description="Sudoku service that allows playing Sudoku game"

WORKDIR /usr/src/app

COPY . .

RUN pip install -r requirements.txt

EXPOSE 10000

# Start test
ENTRYPOINT ["python", "-m", "unittest", "discover"]